version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: legal_services
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=legal_services
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html
